// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFfrZzf16DAkYUYQeVJHzWIpLNp289UiA',
    appId: '1:774900811724:web:108079558228f0c71a3f69',
    messagingSenderId: '774900811724',
    projectId: 'flutter-tiktok-clone-bf902',
    authDomain: 'flutter-tiktok-clone-bf902.firebaseapp.com',
    storageBucket: 'flutter-tiktok-clone-bf902.firebasestorage.app',
    measurementId: 'G-DEP1S17N0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc-KIcadun-g58qGrvTqmAVy2iLqeZHKQ',
    appId: '1:774900811724:android:e9f0f9bfad858aa71a3f69',
    messagingSenderId: '774900811724',
    projectId: 'flutter-tiktok-clone-bf902',
    storageBucket: 'flutter-tiktok-clone-bf902.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEOH98EosV-SRxfi6HPX5H_zK-1MMvgm0',
    appId: '1:774900811724:ios:290106d1ee7789f41a3f69',
    messagingSenderId: '774900811724',
    projectId: 'flutter-tiktok-clone-bf902',
    storageBucket: 'flutter-tiktok-clone-bf902.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );
}
